apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: statusquarkusio-vvtd
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-diof-tenant/status-quarkus-io/statusquarkusio-vvtd@sha256:b1fdda1d83e1499c0010f154c76847a2f412039749f3281d4242fb8133688abb
        name: my-java-quarkus
        resources: {}
status: {}
