apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: statusquarkusio-vvtd
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: statusquarkusio-vvtd
    app.kubernetes.io/part-of: status-quarkus-io
  name: statusquarkusio-vvtd
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: statusquarkusio-vvtd
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: statusquarkusio-vvtd
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-diof-tenant/status-quarkus-io/statusquarkusio-vvtd@sha256:b1fdda1d83e1499c0010f154c76847a2f412039749f3281d4242fb8133688abb
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        - containerPort: 9081
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
